# Generated by Django 5.0.3 on 2024-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_bookings_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cab",
            name="state",
            field=models.CharField(
                choices=[("IDLE", "IDLE"), ("ON_TRIP", "ON_TRIP")],
                default="IDLE",
                max_length=10,
            ),
        ),
    ]
