# Generated by Django 5.0.3 on 2024-03-13 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_bookings_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="booking_city",
            new_name="city",
        ),
    ]
